name: BuildAndTest

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.303
    - name: Install dependencies
      run: dotnet restore
    - name: Build with dotnet
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    # - name: Use Node.js 20
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: "20.x"
    # - name: Build Project 
    #   run: |
    #     cd sujiraw.client
    #     npm install
    #     npm run build
    - name: Publish
      run: dotnet publish -c Release --os linux --output ./Release
    - name: deploy file
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        username: ${{ secrets.FTP_USERNAME }}
        server: 'sujiraw.kamelong.com'
        port: '22'
        local_path: './Release/*'
        remote_path: '/ftp_kamelong/Sujiraw/'
        sftp_only: true
        password: ${{ secrets.FTP_PASSWORD }}
    - name: Restart App Server development
      uses: appleboy/ssh-action@master
      with:
        host: 'sujiraw.kamelong.com'
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{secrets.SSH_PASSPHRASE}}
        port: '22'
        script: |
          sudo systemctl restart sujiraw
